# Generated by Django 4.1.1 on 2022-09-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_profile_first_name_alter_profile_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="patronymic",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="slug",
            field=models.SlugField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="social_network_link",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
