version: '3.3'
services:

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=shop
      - POSTGRES_PASSWORD=shop
  redis:
    image: redis:latest
  django:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - REDIS_HOST=redis
    command: |
      python manage.py runserver 0.0.0.0:8000
  worker:
    image: dedrobin/django:latest
    volumes:
      - ./:/app/
    depends_on:
      - redis
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - REDIS_HOST=redis
    command: |
      python manage.py rqworker default
