# Generated by Django 4.1.1 on 2022-09-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_favoriteproduct_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="comment",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
